// lib/models/bbps_models.dart

// ── Biller Category ───────────────────────────────────────────────────────────
class BillerCategory {
  final String id;
  final String name;
  final String? icon;

  BillerCategory({required this.id, required this.name, this.icon});

  factory BillerCategory.fromJson(Map<String, dynamic> json) => BillerCategory(
        id: json['id']?.toString() ?? json['categoryId']?.toString() ?? '',
        name: json['name'] ?? json['categoryName'] ?? '',
        icon: json['icon'],
      );
}

// ── Biller ────────────────────────────────────────────────────────────────────
class Biller {
  final String id;
  final String name;
  final String categoryId;
  final List<BillerParam> params; // fields required for this biller

  Biller({required this.id, required this.name, required this.categoryId, required this.params});

  factory Biller.fromJson(Map<String, dynamic> json) => Biller(
        id: json['billerId']?.toString() ?? json['id']?.toString() ?? '',
        name: json['billerName'] ?? json['name'] ?? '',
        categoryId: json['categoryId']?.toString() ?? '',
        params: (json['customerParams'] as List<dynamic>? ?? [])
            .map((p) => BillerParam.fromJson(p))
            .toList(),
      );
}

class BillerParam {
  final String name;
  final String label;
  final bool optional;

  BillerParam({required this.name, required this.label, required this.optional});

  factory BillerParam.fromJson(Map<String, dynamic> json) => BillerParam(
        name: json['paramName'] ?? json['name'] ?? '',
        label: json['paramLabel'] ?? json['label'] ?? '',
        optional: json['optional'] == true || json['optional'] == 'true',
      );
}

// ── Fetch Bill Result ─────────────────────────────────────────────────────────
// Stored in memory after fetchBill — passed back as-is to payBill
class FetchBillResult {
  final String merchantRefId;   // generated by backend, MUST reuse for pay
  final Map<String, dynamic> rawResult; // full VimoPay response stored here
  final double? billAmount;
  final String? billDueDate;
  final String? billerName;
  final String? consumerName;

  FetchBillResult({
    required this.merchantRefId,
    required this.rawResult,
    this.billAmount,
    this.billDueDate,
    this.billerName,
    this.consumerName,
  });

  factory FetchBillResult.fromApiResponse(Map<String, dynamic> json) {
    final raw = json['fetchBillResult'] as Map<String, dynamic>? ?? {};
    return FetchBillResult(
      merchantRefId: json['merchantRefId'] ?? '',
      rawResult: raw,
      billAmount: _parseDouble(json['billAmount'] ?? raw['billAmount']),
      billDueDate: json['billDueDate']?.toString() ?? raw['billDueDate']?.toString(),
      billerName: json['billerName']?.toString() ?? raw['billerName']?.toString(),
      consumerName: raw['consumerName']?.toString(),
    );
  }

  static double? _parseDouble(dynamic v) {
    if (v == null) return null;
    return double.tryParse(v.toString());
  }
}

// ── Pay Bill Result ───────────────────────────────────────────────────────────
class PayBillResult {
  final bool success;
  final String message;
  final int? transactionId;
  final String? vimoTxnId;
  final bool refunded;

  PayBillResult({
    required this.success,
    required this.message,
    this.transactionId,
    this.vimoTxnId,
    required this.refunded,
  });

  factory PayBillResult.fromJson(Map<String, dynamic> json) => PayBillResult(
        success: json['success'] == true,
        message: json['message'] ?? (json['success'] == true ? 'Payment successful' : 'Payment failed'),
        transactionId: json['transactionId'],
        vimoTxnId: json['vimoTxnId'],
        refunded: json['refunded'] == true,
      );
}
